// GES Sözlüğü (sozluk.html) — editoryal kaynak. Tuple: [Türkçe, English, Deutsch, Русский].
//
// build.js GLOSSARY:STATIC bölgesini buradan doldurur ve DefinedTermSet
// şemasını üretir. Her terimin `id`'si sayfada çapa olur (sozluk.html#kwp) —
// AI yanıt motorları tek terimi bu adresle alıntılar; id'yi DEĞİŞTİRMEYİN.
// KURAL: Bu tanımlar genel bilgidir. Ürüne özel sayı (katsayı, fiyat, verim)
// buraya YAZILMAZ; o değerler config.js'ten ve ürün künyelerinden gelir.
// Mevzuata bağlı terimlerde (mahsuplaşma, lisanssız üretim) kural değişebilir;
// tanım bu yüzden "güncel yönetmeliğe göre" diye çekincelidir.
// Çeviriler build'de sözlüğe eklenir; sözlükte ZATEN olan anahtar ezilmez.
module.exports = {
  labels: {
    title: ["GES Sözlüğü", "Solar Glossary", "Solar-Glossar", "Словарь солнечной энергетики"],
    lead: [
      "Güneş enerjisi, akü ve elektrikli araç dönüşümünde sık geçen terimlerin kısa ve anlaşılır açıklamaları.",
      "Short, plain-language explanations of the terms you meet in solar power, batteries and EV conversion.",
      "Kurze, verständliche Erklärungen der Begriffe rund um Solarenergie, Akkus und die Umrüstung von E-Fahrzeugen.",
      "Краткие и понятные объяснения терминов солнечной энергетики, аккумуляторов и переоснащения электротранспорта."
    ],
    index: ["Terimler", "Terms", "Begriffe", "Термины"],
    ctaTitle: ["Projeniz için teknik bir soru mu var?", "Have a technical question about your project?", "Haben Sie eine technische Frage zu Ihrem Projekt?", "Есть технический вопрос по вашему проекту?"],
    ctaText: [
      "Terimleri sizin sisteminiz üzerinden birlikte açıklayalım.",
      "Let us explain the terms using your own system.",
      "Wir erklären die Begriffe gern anhand Ihrer eigenen Anlage.",
      "Объясним термины на примере вашей системы."
    ]
  },

  terms: [
    { id: "ges",
      term: ["GES (Güneş Enerjisi Santrali)", "Solar power plant (GES)", "Solarkraftwerk (GES)", "Солнечная электростанция (GES)"],
      def: ["Güneş ışığını fotovoltaik panellerle elektriğe dönüştüren sistem. Bina çatısına kurulana çatı GES, zemine kurulana arazi tipi GES denir.",
            "A system that converts sunlight into electricity with photovoltaic panels. In Turkish it is called GES; one built on a roof is a rooftop plant, one built on the ground is a ground-mounted plant.",
            "Eine Anlage, die Sonnenlicht mit Photovoltaikmodulen in Strom umwandelt. Auf Türkisch heißt sie GES; auf dem Dach spricht man von einer Aufdachanlage, auf dem Boden von einer Freiflächenanlage.",
            "Система, преобразующая солнечный свет в электроэнергию с помощью фотоэлектрических панелей. По-турецки она называется GES; станцию на крыше называют крышной, на земле — наземной."],
      link: { href: "hizmetler.html", text: ["Hizmetlerimiz →", "Our services →", "Unsere Leistungen →", "Наши услуги →"] } },
    { id: "fotovoltaik",
      term: ["Fotovoltaik (PV)", "Photovoltaics (PV)", "Photovoltaik (PV)", "Фотоэлектрика (PV)"],
      def: ["Işığın yarı iletken hücrelerde doğrudan elektrik akımına dönüşmesi. Güneş panelleri bu hücrelerden oluşur ve doğru akım (DC) üretir.",
            "The direct conversion of light into electric current in semiconductor cells. Solar panels are made of these cells and produce direct current (DC).",
            "Die direkte Umwandlung von Licht in elektrischen Strom in Halbleiterzellen. Solarmodule bestehen aus solchen Zellen und erzeugen Gleichstrom (DC).",
            "Прямое преобразование света в электрический ток в полупроводниковых элементах. Солнечные панели состоят из таких элементов и вырабатывают постоянный ток (DC)."] },
    { id: "stc",
      term: ["STC (Standart Test Koşulları)", "STC (Standard Test Conditions)", "STC (Standard-Testbedingungen)", "STC (стандартные условия испытаний)"],
      def: ["1000 W/m² ışınım, 25 °C hücre sıcaklığı ve AM 1,5 ışık spektrumu. Panel etiketindeki güç ve elektriksel değerler bu koşullarda ölçülür; sahadaki gerçek üretim sıcaklığa ve ışınıma göre farklıdır.",
            "1000 W/m² irradiance, 25 °C cell temperature and an AM 1.5 light spectrum. The power and electrical values on a panel label are measured under these conditions; real output in the field varies with temperature and irradiance.",
            "1000 W/m² Einstrahlung, 25 °C Zelltemperatur und ein Lichtspektrum von AM 1,5. Leistung und elektrische Werte auf dem Modulschild werden unter diesen Bedingungen gemessen; der reale Ertrag hängt von Temperatur und Einstrahlung ab.",
            "Освещённость 1000 Вт/м², температура элемента 25 °C и спектр AM 1,5. Мощность и электрические параметры на этикетке панели измеряются в этих условиях; реальная выработка зависит от температуры и освещённости."] },
    { id: "kwp",
      term: ["Wp / kWp (tepe güç)", "Wp / kWp (peak power)", "Wp / kWp (Spitzenleistung)", "Wp / kWp (пиковая мощность)"],
      def: ["Watt-peak: panelin standart test koşullarındaki (STC) tepe gücü. 1 kWp = 1000 Wp; örneğin 540 Wp gücündeki 10 panel 5,4 kWp kurulu güç eder. Sistem büyüklüğü kWp ile ifade edilir.",
            "Watt-peak: the peak power of a panel under standard test conditions (STC). 1 kWp = 1000 Wp; for example, ten 540 Wp panels make 5.4 kWp of installed capacity. System size is expressed in kWp.",
            "Watt-Peak: die Spitzenleistung eines Moduls unter Standard-Testbedingungen (STC). 1 kWp = 1000 Wp; zehn Module mit je 540 Wp ergeben zum Beispiel 5,4 kWp installierte Leistung. Die Anlagengröße wird in kWp angegeben.",
            "Ватт-пик: пиковая мощность панели в стандартных условиях испытаний (STC). 1 kWp = 1000 Wp; например, 10 панелей по 540 Wp дают 5,4 kWp установленной мощности. Размер системы выражается в kWp."] },
    { id: "kwh",
      term: ["kWh ve kW", "kWh and kW", "kWh und kW", "кВт·ч и кВт"],
      def: ["kWh (kilovatsaat) enerji miktarıdır: 1 kW güçteki bir cihaz 1 saat çalışınca 1 kWh tüketir. Elektrik faturası ve akü kapasitesi kWh ile, aynı anda çekilen güç ise kW ile ifade edilir.",
            "kWh (kilowatt-hour) is an amount of energy: a 1 kW appliance running for one hour uses 1 kWh. Electricity bills and battery capacity are given in kWh, while the power drawn at a given moment is given in kW.",
            "kWh (Kilowattstunde) ist eine Energiemenge: Ein Gerät mit 1 kW Leistung verbraucht in einer Stunde 1 kWh. Stromrechnung und Akkukapazität werden in kWh angegeben, die momentan bezogene Leistung in kW.",
            "кВт·ч (киловатт-час) — это количество энергии: прибор мощностью 1 кВт за час работы потребляет 1 кВт·ч. Счёт за электричество и ёмкость аккумулятора указывают в кВт·ч, а мощность, потребляемую в данный момент, — в кВт."] },
    { id: "monokristal",
      term: ["Monokristal panel", "Monocrystalline panel", "Monokristallines Modul", "Монокристаллическая панель"],
      def: ["Tek kristal silisyumdan üretilen hücrelerle yapılan panel. Polikristale göre verimi yüksektir, aynı alandan daha fazla güç alınır. Günümüzde satılan panellerin büyük bölümü monokristaldir.",
            "A panel made with cells cut from single-crystal silicon. It is more efficient than polycrystalline, so the same area delivers more power. Most panels sold today are monocrystalline.",
            "Ein Modul aus Zellen aus einkristallinem Silizium. Es hat einen höheren Wirkungsgrad als polykristalline Module und liefert mehr Leistung pro Fläche. Die meisten heute verkauften Module sind monokristallin.",
            "Панель из элементов на основе монокристаллического кремния. Её КПД выше, чем у поликристаллической, поэтому с той же площади получается больше мощности. Большинство продаваемых сегодня панелей монокристаллические."] },
    { id: "topcon",
      term: ["TOPCon hücre", "TOPCon cell", "TOPCon-Zelle", "Элемент TOPCon"],
      def: ["Tunnel Oxide Passivated Contact: N-tipi silisyum hücrelerde kullanılan, arka yüzeydeki ince oksit ve polisilisyum katmanla kayıpları azaltan hücre teknolojisi. PERC hücrelere göre daha yüksek verim ve sıcakta daha az kayıp hedefler.",
            "Tunnel Oxide Passivated Contact: a cell technology for N-type silicon that reduces losses with a thin oxide and polysilicon layer on the rear surface. It aims for higher efficiency and lower heat losses than PERC cells.",
            "Tunnel Oxide Passivated Contact: eine Zelltechnologie für n-Typ-Silizium, die mit einer dünnen Oxid- und Polysiliziumschicht auf der Rückseite Verluste verringert. Sie zielt auf einen höheren Wirkungsgrad und geringere Wärmeverluste als PERC-Zellen.",
            "Tunnel Oxide Passivated Contact: технология элементов на кремнии N-типа, снижающая потери за счёт тонкого оксидного и поликремниевого слоя на тыльной стороне. По сравнению с PERC рассчитана на более высокий КПД и меньшие потери при нагреве."],
      link: { href: "online-satis.html", text: ["Satıştaki paneller →", "Panels on sale →", "Module im Shop →", "Панели в продаже →"] } },
    { id: "perc",
      term: ["PERC hücre", "PERC cell", "PERC-Zelle", "Элемент PERC"],
      def: ["Passivated Emitter and Rear Cell: hücrenin arka yüzeyine eklenen pasivasyon katmanıyla verimi artıran, yaygın P-tipi hücre teknolojisi.",
            "Passivated Emitter and Rear Cell: a widely used P-type cell technology that raises efficiency with a passivation layer on the rear of the cell.",
            "Passivated Emitter and Rear Cell: eine verbreitete p-Typ-Zelltechnologie, die den Wirkungsgrad mit einer Passivierungsschicht auf der Zellrückseite erhöht.",
            "Passivated Emitter and Rear Cell: распространённая технология элементов P-типа, повышающая КПД за счёт пассивирующего слоя на тыльной стороне."] },
    { id: "yarim-hucre",
      term: ["Yarım hücre (half-cut)", "Half-cut cells", "Halbzellen (half-cut)", "Половинчатые элементы (half-cut)"],
      def: ["Hücrelerin ikiye kesilerek bağlandığı panel tasarımı. Her yarımdan geçen akım azaldığı için direnç kayıpları düşer; kısmi gölgelenmede üretim daha az etkilenir.",
            "A panel design in which cells are cut in half before being connected. Less current flows through each half, so resistive losses fall and partial shading affects output less.",
            "Ein Moduldesign, bei dem die Zellen halbiert und dann verschaltet werden. Durch jede Hälfte fließt weniger Strom, dadurch sinken die Widerstandsverluste und Teilverschattung wirkt sich weniger aus.",
            "Конструкция панели, в которой элементы разрезаны пополам. Ток через каждую половину меньше, поэтому снижаются резистивные потери, а частичное затенение меньше влияет на выработку."] },
    { id: "inverter",
      term: ["İnverter (evirici)", "Inverter", "Wechselrichter", "Инвертор"],
      def: ["Panellerin ürettiği doğru akımı (DC), evde ve şebekede kullanılan 230 V alternatif akıma (AC) dönüştüren cihaz. Şebeke bağlantılı, off-grid ve hibrit türleri vardır.",
            "A device that converts the direct current (DC) produced by the panels into the 230 V alternating current (AC) used at home and on the grid. There are grid-tied, off-grid and hybrid types.",
            "Ein Gerät, das den von den Modulen erzeugten Gleichstrom (DC) in den im Haus und im Netz genutzten 230-V-Wechselstrom (AC) umwandelt. Es gibt netzgekoppelte, Insel- und Hybrid-Wechselrichter.",
            "Устройство, преобразующее постоянный ток (DC) от панелей в переменный ток 230 В (AC), который используется дома и в сети. Бывают сетевые, автономные и гибридные инверторы."] },
    { id: "on-grid",
      term: ["On-grid (şebeke bağlantılı) sistem", "On-grid (grid-tied) system", "Netzgekoppelte Anlage (on-grid)", "Сетевая система (on-grid)"],
      def: ["Şebekeye bağlı çalışan sistem: üretilen elektrik önce binada tüketilir, fazlası şebekeye verilir. Güvenlik gereği elektrik kesintisinde otomatik olarak durur.",
            "A system that works connected to the grid: electricity is used in the building first and the surplus goes to the grid. For safety it shuts down automatically during a power cut.",
            "Eine Anlage am Stromnetz: Der Strom wird zuerst im Gebäude verbraucht, der Überschuss geht ins Netz. Aus Sicherheitsgründen schaltet sie sich bei einem Stromausfall automatisch ab.",
            "Система, работающая с подключением к сети: энергия сначала потребляется в здании, излишек уходит в сеть. В целях безопасности при отключении электричества она автоматически останавливается."] },
    { id: "off-grid",
      term: ["Off-grid (şebekeden bağımsız) sistem", "Off-grid system", "Inselanlage (off-grid)", "Автономная система (off-grid)"],
      def: ["Şebekeye bağlı olmayan sistem: panel, akü ve inverterle kendi elektriğini üretir ve depolar. Bağ evi, karavan, tarla ve şebekenin ulaşmadığı yerlerde kullanılır.",
            "A system that is not connected to the grid: it generates and stores its own electricity with panels, a battery and an inverter. It is used in cabins, caravans, fields and places the grid does not reach.",
            "Eine Anlage ohne Netzanschluss: Sie erzeugt und speichert ihren Strom mit Modulen, Akku und Wechselrichter. Sie wird in Gartenhäusern, Wohnmobilen, auf Feldern und überall dort eingesetzt, wo kein Netz hinreicht.",
            "Система без подключения к сети: она сама вырабатывает и накапливает электроэнергию с помощью панелей, аккумулятора и инвертора. Применяется на дачах, в караванах, на полях и там, куда не доходит сеть."],
      link: { href: "sistem-kur.html", text: ["Sistem Kurucu →", "System Builder →", "System-Konfigurator →", "Конфигуратор системы →"] } },
    { id: "hibrit",
      term: ["Hibrit sistem", "Hybrid system", "Hybridanlage", "Гибридная система"],
      def: ["Şebekeye bağlı çalışırken akü de kullanan sistem. Gündüz üretimini depolayıp akşam kullanır; kesintide tasarımda seçilen yükleri aküden beslemeye devam eder.",
            "A system that is grid-connected but also uses a battery. It stores daytime output for the evening and, during an outage, keeps the loads chosen in the design running from the battery.",
            "Eine netzgekoppelte Anlage, die zusätzlich einen Akku nutzt. Sie speichert den Tagesertrag für den Abend und versorgt bei einem Stromausfall die bei der Planung ausgewählten Verbraucher weiter aus dem Akku.",
            "Система, подключённая к сети и одновременно использующая аккумулятор. Она запасает дневную выработку на вечер, а при отключении продолжает питать от аккумулятора выбранные при проектировании нагрузки."],
      link: { href: "enerji-depolama.html", text: ["Enerji depolama →", "Energy storage →", "Energiespeicher →", "Накопители энергии →"] } },
    { id: "mppt",
      term: ["MPPT (en yüksek güç noktası izleme)", "MPPT (maximum power point tracking)", "MPPT (Maximum Power Point Tracking)", "MPPT (отслеживание точки максимальной мощности)"],
      def: ["Panelin o anki ışık ve sıcaklıkta en fazla güç verdiği gerilim-akım noktasını sürekli bulan kontrol yöntemi. Şarj kontrol cihazlarında ve inverterlerde bulunur.",
            "A control method that continuously finds the voltage–current point at which the panel delivers the most power in the current light and temperature. It is built into charge controllers and inverters.",
            "Ein Regelverfahren, das laufend den Spannungs-Strom-Punkt sucht, an dem das Modul bei aktuellem Licht und aktueller Temperatur die meiste Leistung liefert. Es steckt in Ladereglern und Wechselrichtern.",
            "Метод управления, который постоянно находит точку напряжения и тока, при которой панель отдаёт наибольшую мощность при текущих освещённости и температуре. Используется в контроллерах заряда и инверторах."] },
    { id: "boost-mppt",
      term: ["BOOST MPPT şarj kontrol cihazı", "BOOST MPPT charge controller", "BOOST-MPPT-Laderegler", "Контроллер заряда BOOST MPPT"],
      def: ["Panel gerilimini akü grubunun geriliminin üzerine yükselterek şarj eden MPPT şarj kontrol cihazı. Daha düşük gerilimli panellerle 24–72 V akü gruplarını, örneğin elektrikli araç akülerini şarj etmeyi sağlar.",
            "An MPPT charge controller that boosts the panel voltage above the battery-pack voltage to charge it. It lets lower-voltage panels charge 24–72 V battery packs, such as electric-vehicle batteries.",
            "Ein MPPT-Laderegler, der die Modulspannung über die Akkuspannung anhebt, um zu laden. So können Module mit niedrigerer Spannung Akkupacks von 24–72 V laden, etwa die Akkus von Elektrofahrzeugen.",
            "MPPT-контроллер заряда, который повышает напряжение панели выше напряжения аккумуляторного блока, чтобы его зарядить. Позволяет панелям с более низким напряжением заряжать блоки 24–72 В, например аккумуляторы электротранспорта."],
      link: { href: "elektrikli-arac-donusum.html", text: ["BOOST MPPT ürün sayfası →", "BOOST MPPT product page →", "BOOST-MPPT-Produktseite →", "Страница товара BOOST MPPT →"] } },
    { id: "lifepo4",
      term: ["LiFePO₄ (lityum demir fosfat) akü", "LiFePO₄ (lithium iron phosphate) battery", "LiFePO₄-Akku (Lithium-Eisenphosphat)", "Аккумулятор LiFePO₄ (литий-железо-фосфат)"],
      def: ["Lityum demir fosfat kimyalı lityum akü. Uzun çevrim ömrü, yüksek kullanılabilir kapasitesi ve termal kararlılığı nedeniyle güneş enerjisi depolamada ve elektrikli araçlarda yaygındır.",
            "A lithium battery with lithium iron phosphate chemistry. Its long cycle life, high usable capacity and thermal stability make it common in solar storage and electric vehicles.",
            "Ein Lithium-Akku mit Lithium-Eisenphosphat-Chemie. Wegen seiner hohen Zyklenfestigkeit, großen nutzbaren Kapazität und thermischen Stabilität ist er in Solarspeichern und Elektrofahrzeugen verbreitet.",
            "Литиевый аккумулятор с химией литий-железо-фосфат. Благодаря большому ресурсу циклов, высокой полезной ёмкости и термической стабильности широко применяется в солнечных накопителях и электротранспорте."],
      link: { href: "aku-lifepo4-72v-30ah.html", text: ["72 V LiFePO₄ çekiş aküsü →", "72 V LiFePO₄ traction battery →", "72-V-LiFePO₄-Traktionsakku →", "Тяговый аккумулятор LiFePO₄ 72 В →"] } },
    { id: "jel-agm",
      term: ["Jel ve AGM akü", "Gel and AGM batteries", "Gel- und AGM-Akkus", "Гелевые и AGM-аккумуляторы"],
      def: ["Kurşun-asit akünün bakım gerektirmeyen türleri: elektrolit jel içinde (jel) ya da cam elyafa emdirilmiş (AGM) hâldedir. İlk maliyeti düşüktür; ancak derin deşarj ömrünü kısaltır ve kullanılabilir kapasitesi lityuma göre sınırlıdır.",
            "Maintenance-free types of lead-acid battery: the electrolyte is held in a gel (gel) or absorbed in glass fibre (AGM). They cost less up front, but deep discharges shorten their life and their usable capacity is more limited than lithium.",
            "Wartungsfreie Bleiakku-Varianten: Der Elektrolyt ist in einem Gel gebunden (Gel) oder in Glasfaservlies aufgesaugt (AGM). Sie sind in der Anschaffung günstiger, doch Tiefentladungen verkürzen ihre Lebensdauer und die nutzbare Kapazität ist geringer als bei Lithium.",
            "Необслуживаемые разновидности свинцово-кислотных аккумуляторов: электролит находится в геле (гелевые) или пропитывает стекловолокно (AGM). Они дешевле при покупке, но глубокие разряды сокращают их срок службы, а полезная ёмкость меньше, чем у литиевых."] },
    { id: "dod",
      term: ["DoD (deşarj derinliği)", "DoD (depth of discharge)", "DoD (Entladetiefe)", "DoD (глубина разряда)"],
      def: ["Akü kapasitesinin ne kadarının kullanıldığı. Örneğin %80 DoD, kapasitenin %80'inin çekildiği anlamına gelir. Akünün izin verdiği DoD ne kadar yüksekse kullanılabilir kapasite o kadar büyüktür.",
            "How much of a battery's capacity is used. For example, 80% DoD means 80% of the capacity has been drawn. The higher the DoD a battery allows, the larger its usable capacity.",
            "Wie viel der Akkukapazität genutzt wird. 80 % DoD bedeutet zum Beispiel, dass 80 % der Kapazität entnommen wurden. Je höher die zulässige Entladetiefe, desto größer die nutzbare Kapazität.",
            "Какая часть ёмкости аккумулятора используется. Например, DoD 80% означает, что израсходовано 80% ёмкости. Чем выше допустимая глубина разряда, тем больше полезная ёмкость."] },
    { id: "bms",
      term: ["BMS (akü yönetim sistemi)", "BMS (battery management system)", "BMS (Batteriemanagementsystem)", "BMS (система управления батареей)"],
      def: ["Lityum akü hücrelerinin gerilimini, akımını ve sıcaklığını izleyen; aşırı şarj, aşırı deşarj ve kısa devreye karşı koruyan ve hücreleri dengeleyen elektronik devre.",
            "An electronic circuit that monitors the voltage, current and temperature of lithium battery cells, protects against overcharge, over-discharge and short circuits, and balances the cells.",
            "Eine Elektronik, die Spannung, Strom und Temperatur der Lithiumzellen überwacht, vor Überladung, Tiefentladung und Kurzschluss schützt und die Zellen ausgleicht.",
            "Электронная схема, которая контролирует напряжение, ток и температуру литиевых элементов, защищает от перезаряда, глубокого разряда и короткого замыкания и балансирует элементы."] },
    { id: "cevrim-omru",
      term: ["Çevrim (döngü) ömrü", "Cycle life", "Zyklenlebensdauer", "Ресурс циклов"],
      def: ["Akünün tam şarj-deşarj döngüsünü kaç kez tekrarlayabileceği; genellikle kapasitenin belirli bir orana düştüğü nokta esas alınır. Değer deşarj derinliğine ve sıcaklığa bağlıdır ve ürün künyesinde yazılır.",
            "How many full charge–discharge cycles a battery can go through, usually counted until its capacity falls to a set percentage. The figure depends on depth of discharge and temperature and is stated in the product data sheet.",
            "Wie viele volle Lade-Entlade-Zyklen ein Akku durchlaufen kann, meist gezählt, bis die Kapazität auf einen festgelegten Anteil sinkt. Der Wert hängt von Entladetiefe und Temperatur ab und steht im Produktdatenblatt.",
            "Сколько полных циклов заряда-разряда выдерживает аккумулятор; обычно считают до снижения ёмкости до установленной доли. Значение зависит от глубины разряда и температуры и указывается в паспорте изделия."] },
    { id: "mahsuplasma",
      term: ["Mahsuplaşma", "Net metering (mahsuplaşma)", "Saldierung (mahsuplaşma)", "Взаимозачёт (mahsuplaşma)"],
      def: ["Şebekeye verilen ve şebekeden çekilen elektriğin, mevzuatta belirlenen dönem içinde birbirinden düşülerek faturalandırılması. Hangi dönemin (örneğin aylık ya da saatlik) uygulandığı bağlantı tipine ve güncel yönetmeliğe göre değişir.",
            "Billing in which the electricity fed into the grid and the electricity drawn from it are offset against each other within the period set by regulation. Which period applies (for example monthly or hourly) depends on the connection type and the current rules in Türkiye.",
            "Abrechnung, bei der eingespeister und bezogener Strom innerhalb des gesetzlich festgelegten Zeitraums gegeneinander verrechnet werden. Welcher Zeitraum gilt (zum Beispiel monatlich oder stündlich), hängt vom Anschlusstyp und den aktuellen Vorschriften in der Türkei ab.",
            "Расчёт, при котором отданная в сеть и полученная из сети электроэнергия взаимно вычитаются в течение периода, установленного законодательством. Какой период применяется (например, месячный или почасовой), зависит от типа подключения и действующих правил в Турции."] },
    { id: "lisanssiz-uretim",
      term: ["Lisanssız elektrik üretimi", "Licence-exempt generation", "Lizenzfreie Stromerzeugung", "Безлицензионная генерация"],
      def: ["Üretim lisansı almadan, öncelikle kendi tüketimini karşılamak amacıyla kurulan elektrik üretim tesisi. Kapasite sınırları, başvuru ve bağlantı süreçleri ilgili yönetmelik ve dağıtım şirketi tarafından belirlenir.",
            "A generation plant built without a generation licence, mainly to cover the owner's own consumption. Capacity limits, the application and the grid connection process are set by the relevant regulation and the distribution company.",
            "Eine Erzeugungsanlage ohne Erzeugungslizenz, die vor allem den Eigenverbrauch decken soll. Leistungsgrenzen, Antrag und Netzanschluss regeln die einschlägige Verordnung und der Verteilnetzbetreiber.",
            "Генерирующая установка без лицензии на производство, созданная прежде всего для собственного потребления. Предельная мощность, порядок подачи заявки и подключения определяются соответствующим регламентом и распределительной компанией."] },
    { id: "oz-tuketim",
      term: ["Öz tüketim", "Self-consumption", "Eigenverbrauch", "Собственное потребление"],
      def: ["Üretilen güneş elektriğinin şebekeye verilmeden, üretildiği anda binada kullanılan kısmı. Öz tüketim oranı yükseldikçe tasarruf artar; gündüz çalışan cihazlar ve batarya bu oranı yükseltir.",
            "The share of solar electricity used in the building at the moment it is produced, instead of being fed into the grid. The higher the self-consumption rate, the greater the savings; appliances that run during the day and a battery raise it.",
            "Der Anteil des Solarstroms, der im Moment der Erzeugung im Gebäude genutzt statt ins Netz eingespeist wird. Je höher die Eigenverbrauchsquote, desto größer die Ersparnis; tagsüber laufende Geräte und ein Akku erhöhen sie.",
            "Доля солнечной энергии, которая используется в здании в момент выработки, а не отдаётся в сеть. Чем выше доля собственного потребления, тем больше экономия; её повышают приборы, работающие днём, и аккумулятор."] },
    { id: "degradasyon",
      term: ["Degradasyon (verim kaybı)", "Degradation", "Degradation", "Деградация"],
      def: ["Panel veriminin yıllar içinde yavaş yavaş azalması. Üreticiler yıllık kayıp oranını ve garanti süresi sonunda panelin vermesi gereken gücü künyede belirtir.",
            "The slow decline of a panel's efficiency over the years. Manufacturers state the annual loss rate and the power the panel must still deliver at the end of the warranty in the data sheet.",
            "Der langsame Rückgang des Modulwirkungsgrads über die Jahre. Hersteller geben im Datenblatt die jährliche Verlustrate und die am Ende der Garantie noch zugesicherte Leistung an.",
            "Постепенное снижение КПД панели с годами. Производители указывают в паспорте годовой процент потерь и мощность, которую панель должна выдавать в конце гарантийного срока."] },
    { id: "ozgul-uretim",
      term: ["Özgül üretim (kWh/kWp)", "Specific yield (kWh/kWp)", "Spezifischer Ertrag (kWh/kWp)", "Удельная выработка (кВт·ч/kWp)"],
      def: ["Bir yılda 1 kWp kurulu gücün ürettiği enerji. Bölgenin güneşlenmesine, panellerin yönüne ve eğimine bağlıdır; Antalya gibi güneşli bölgelerde yüksektir ve tasarruf hesabının temelidir.",
            "The energy that 1 kWp of installed capacity produces in a year. It depends on the local sunshine and the direction and tilt of the panels; it is high in sunny regions such as Antalya and is the basis of the savings calculation.",
            "Die Energie, die 1 kWp installierte Leistung in einem Jahr erzeugt. Sie hängt von der Sonneneinstrahlung vor Ort sowie Ausrichtung und Neigung der Module ab; in sonnigen Regionen wie Antalya ist sie hoch und bildet die Grundlage der Einsparungsrechnung.",
            "Энергия, которую 1 kWp установленной мощности вырабатывает за год. Зависит от солнечности региона, ориентации и наклона панелей; в солнечных регионах, таких как Анталья, она высокая и лежит в основе расчёта экономии."],
      link: { href: "hesaplayici.html", text: ["Tasarruf hesaplayıcı →", "Savings calculator →", "Einsparungsrechner →", "Калькулятор экономии →"] } },
    { id: "performans-orani",
      term: ["Performans oranı (PR)", "Performance ratio (PR)", "Performance Ratio (PR)", "Коэффициент производительности (PR)"],
      def: ["Sistemin gerçek üretiminin, aynı ışınımda teorik olarak üretebileceği enerjiye oranı. Sıcaklık, kablo, inverter ve kirlenme kayıplarını tek sayıda özetler; izlemede sistemin sağlığını gösterir.",
            "The ratio of a system's actual output to the energy it could theoretically produce under the same irradiance. It sums up temperature, cable, inverter and soiling losses in a single figure and shows the health of the system in monitoring.",
            "Das Verhältnis des tatsächlichen Ertrags zur Energie, die die Anlage bei gleicher Einstrahlung theoretisch erzeugen könnte. Es fasst Temperatur-, Kabel-, Wechselrichter- und Verschmutzungsverluste in einer Zahl zusammen und zeigt im Monitoring den Zustand der Anlage.",
            "Отношение фактической выработки системы к энергии, которую она теоретически могла бы выработать при той же освещённости. Сводит в одно число потери от нагрева, в кабелях, инверторе и от загрязнения и при мониторинге показывает состояние системы."] },
    { id: "mc4",
      term: ["MC4 konnektör", "MC4 connector", "MC4-Stecker", "Разъём MC4"],
      def: ["Paneller arasındaki ve panel ile cihaz arasındaki DC bağlantılarda kullanılan standart, kilitli erkek-dişi konnektör. Bağlantı güvenliği için uygun pense ile sıkılması gerekir.",
            "The standard locking male–female connector used for DC connections between panels and between a panel and a device. It must be crimped with the proper tool for a safe connection.",
            "Der genormte, verriegelbare Stecker-Buchse-Verbinder für DC-Verbindungen zwischen Modulen sowie zwischen Modul und Gerät. Für eine sichere Verbindung muss er mit dem passenden Werkzeug gecrimpt werden.",
            "Стандартный разъём «папа-мама» с фиксацией для соединений постоянного тока между панелями, а также между панелью и устройством. Для надёжного соединения его нужно обжимать подходящим инструментом."] },
    { id: "dizi",
      term: ["Dizi (string)", "String", "String (Modulstrang)", "Цепочка (string)"],
      def: ["Seri bağlanmış panel grubu. Seri bağlantıda gerilimler toplanır; dizideki panel sayısı inverterin ya da şarj cihazının giriş gerilimi aralığına göre belirlenir.",
            "A group of panels connected in series. Voltages add up in series, so the number of panels in a string is chosen to fit the input voltage range of the inverter or charge controller.",
            "Eine Gruppe in Reihe geschalteter Module. In Reihe addieren sich die Spannungen, deshalb richtet sich die Modulanzahl eines Strings nach dem Eingangsspannungsbereich des Wechselrichters oder Ladereglers.",
            "Группа последовательно соединённых панелей. При последовательном соединении напряжения складываются, поэтому количество панелей в цепочке подбирают под диапазон входного напряжения инвертора или контроллера заряда."] },
    { id: "voc-isc",
      term: ["Voc ve Isc", "Voc and Isc", "Voc und Isc", "Voc и Isc"],
      def: ["Açık devre gerilimi (Voc) ve kısa devre akımı (Isc): panelin standart test koşullarındaki sınır değerleri. Dizi tasarımında, soğuk havada yükselen Voc'nin cihazın azami giriş gerilimini aşmaması gerekir.",
            "Open-circuit voltage (Voc) and short-circuit current (Isc): the limit values of a panel under standard test conditions. When designing a string, Voc, which rises in cold weather, must not exceed the device's maximum input voltage.",
            "Leerlaufspannung (Voc) und Kurzschlussstrom (Isc): die Grenzwerte eines Moduls unter Standard-Testbedingungen. Bei der String-Planung darf die bei Kälte steigende Voc die maximale Eingangsspannung des Geräts nicht überschreiten.",
            "Напряжение холостого хода (Voc) и ток короткого замыкания (Isc): предельные значения панели в стандартных условиях испытаний. При проектировании цепочки Voc, которое растёт в холодную погоду, не должно превышать максимальное входное напряжение устройства."] },
    { id: "golgelenme",
      term: ["Gölgelenme ve sıra aralığı", "Shading and row spacing", "Verschattung und Reihenabstand", "Затенение и расстояние между рядами"],
      def: ["Panele düşen gölge yalnız o paneli değil bağlı olduğu diziyi de etkileyebilir. Arazi kurulumlarında sıraların birbirini gölgelememesi için sıra aralığı, kış gündönümündeki güneş açısına göre hesaplanır.",
            "A shadow on one panel can affect the whole string it is connected to, not just that panel. In ground-mounted plants the row spacing is calculated from the sun angle at the winter solstice so that rows do not shade each other.",
            "Ein Schatten auf einem Modul kann den gesamten String beeinträchtigen, nicht nur dieses Modul. Bei Freiflächenanlagen wird der Reihenabstand nach dem Sonnenstand zur Wintersonnenwende berechnet, damit sich die Reihen nicht gegenseitig verschatten.",
            "Тень на одной панели может повлиять на всю цепочку, к которой она подключена, а не только на эту панель. На наземных станциях расстояние между рядами рассчитывают по высоте солнца в день зимнего солнцестояния, чтобы ряды не затеняли друг друга."],
      link: { href: "hesaplayici.html", text: ["Mühendislik araçları →", "Engineering tools →", "Technische Werkzeuge →", "Инженерные инструменты →"] } },
    { id: "geri-odeme",
      term: ["Geri ödeme (amortisman) süresi", "Payback period", "Amortisationszeit", "Срок окупаемости"],
      def: ["Yatırım tutarının, sistemin sağladığı tasarrufla geri kazanıldığı süre. Tüketime, elektrik fiyatına, bölgeye ve sistem maliyetine bağlıdır; hesaplayıcı uzun dönem projeksiyonla bu süreyi tahmin eder.",
            "The time it takes for the savings from the system to pay back the investment. It depends on consumption, the electricity price, the region and the system cost; the calculator estimates it with a long-term projection.",
            "Die Zeit, bis die Einsparungen der Anlage die Investition zurückverdient haben. Sie hängt von Verbrauch, Strompreis, Region und Anlagenkosten ab; der Rechner schätzt sie mit einer Langzeitprojektion.",
            "Время, за которое экономия от системы окупает вложения. Зависит от потребления, цены электроэнергии, региона и стоимости системы; калькулятор оценивает этот срок с помощью долгосрочного прогноза."],
      link: { href: "hesaplayici.html", text: ["Tasarruf hesaplayıcı →", "Savings calculator →", "Einsparungsrechner →", "Калькулятор экономии →"] } },
    { id: "epc",
      term: ["EPC (anahtar teslim)", "EPC (turnkey)", "EPC (schlüsselfertig)", "EPC (под ключ)"],
      def: ["Engineering, Procurement, Construction: mühendislik, ekipman tedariki ve kurulumun tek firma tarafından üstlenildiği anahtar teslim proje modeli.",
            "Engineering, Procurement, Construction: a turnkey project model in which one company takes on engineering, equipment supply and installation.",
            "Engineering, Procurement, Construction: ein schlüsselfertiges Projektmodell, bei dem ein Unternehmen Planung, Beschaffung und Montage übernimmt.",
            "Engineering, Procurement, Construction: модель проекта «под ключ», при которой одна компания отвечает за проектирование, поставку оборудования и монтаж."] },
    { id: "om",
      term: ["O&M (işletme ve bakım)", "O&M (operation and maintenance)", "O&M (Betrieb und Wartung)", "O&M (эксплуатация и обслуживание)"],
      def: ["Operation & Maintenance: kurulumdan sonra sistemin izlenmesi, periyodik kontrolü, temizliği ve arızalara müdahale edilmesi.",
            "Operation & Maintenance: monitoring, periodic inspection, cleaning and fault repair of the system after installation.",
            "Operation & Maintenance: Überwachung, regelmäßige Prüfung, Reinigung und Störungsbehebung der Anlage nach der Installation.",
            "Operation & Maintenance: мониторинг, периодические проверки, очистка и устранение неисправностей системы после монтажа."],
      link: { href: "bakim-izleme.html", text: ["GES bakım ve izleme →", "Solar maintenance and monitoring →", "Wartung und Monitoring →", "Обслуживание и мониторинг →"] } },
    { id: "hub-motor",
      term: ["Hub motor (göbek motoru)", "Hub motor", "Nabenmotor", "Мотор-колесо"],
      def: ["Tekerleğin göbeğine yerleştirilmiş elektrik motoru; elektrikli bisiklet, scooter ve triportörlerde yaygındır. Aracın akü gerilimi (örneğin 48, 60 ya da 72 V) motor kontrolörüyle uyumlu olmalıdır.",
            "An electric motor built into the wheel hub, common on e-bikes, scooters and three-wheelers. The vehicle's battery voltage (for example 48, 60 or 72 V) must match the motor controller.",
            "Ein in die Radnabe eingebauter Elektromotor, verbreitet bei E-Bikes, Rollern und Dreirädern. Die Akkuspannung des Fahrzeugs (zum Beispiel 48, 60 oder 72 V) muss zum Motorcontroller passen.",
            "Электродвигатель, встроенный в ступицу колеса; распространён на электровелосипедах, скутерах и трициклах. Напряжение аккумулятора (например, 48, 60 или 72 В) должно соответствовать контроллеру мотора."],
      link: { href: "elektrikli-arac-donusum.html#paketler", text: ["Motor güneş paketleri →", "E-trike solar sets →", "Solar-Sets für Dreiräder →", "Солнечные комплекты для трициклов →"] } }
  ]
};
